#!/bin/sh

cp tensorflow/tensorflow/lite/c/BUILD vai_q_tensorflow/tensorflow/lite/c/
cp tensorflow/tensorflow/lite/delegates/flex/BUILD vai_q_tensorflow/tensorflow/lite/delegates/flex/
cp tensorflow/tensorflow/lite/delegates/gpu/cl/BUILD vai_q_tensorflow/tensorflow/lite/delegates/gpu/cl/
cp tensorflow/tensorflow/lite/delegates/gpu/cl/selectors/BUILD vai_q_tensorflow/tensorflow/lite/delegates/gpu/cl/selectors/
cp tensorflow/tensorflow/lite/delegates/gpu/common/BUILD vai_q_tensorflow/tensorflow/lite/delegates/gpu/common/
cp tensorflow/tensorflow/lite/delegates/gpu/common/testing/BUILD vai_q_tensorflow/tensorflow/lite/delegates/gpu/common/testing/
cp tensorflow/tensorflow/lite/delegates/gpu/common/transformations/BUILD vai_q_tensorflow/tensorflow/lite/delegates/gpu/common/transformations/
cp tensorflow/tensorflow/lite/delegates/gpu/gl/compiler/BUILD vai_q_tensorflow/tensorflow/lite/delegates/gpu/gl/compiler/
cp tensorflow/tensorflow/lite/delegates/gpu/gl/converters/BUILD vai_q_tensorflow/tensorflow/lite/delegates/gpu/gl/converters/
cp tensorflow/tensorflow/lite/delegates/gpu/gl/workgroups/BUILD vai_q_tensorflow/tensorflow/lite/delegates/gpu/gl/workgroups/
cp tensorflow/tensorflow/lite/experimental/c/BUILD vai_q_tensorflow/tensorflow/lite/experimental/c/
cp tensorflow/tensorflow/lite/experimental/micro/testing/BUILD vai_q_tensorflow/tensorflow/lite/experimental/micro/testing/
cp tensorflow/tensorflow/lite/experimental/tensorboard/BUILD vai_q_tensorflow/tensorflow/lite/experimental/tensorboard/
cp tensorflow/tensorflow/lite/experimental/writer/BUILD vai_q_tensorflow/tensorflow/lite/experimental/writer/
cp tensorflow/tensorflow/lite/java/BUILD vai_q_tensorflow/tensorflow/lite/java/
cp tensorflow/tensorflow/lite/java/ovic/BUILD vai_q_tensorflow/tensorflow/lite/java/ovic/
cp tensorflow/tensorflow/lite/java/ovic/src/testdata/BUILD vai_q_tensorflow/tensorflow/lite/java/ovic/src/testdata/
cp tensorflow/tensorflow/lite/kernels/internal/BUILD vai_q_tensorflow/tensorflow/lite/kernels/internal/
cp tensorflow/tensorflow/lite/models/smartreply/BUILD vai_q_tensorflow/tensorflow/lite/models/smartreply/
cp tensorflow/tensorflow/lite/python/interpreter_wrapper/BUILD vai_q_tensorflow/tensorflow/lite/python/interpreter_wrapper/
cp tensorflow/tensorflow/lite/python/optimize/BUILD vai_q_tensorflow/tensorflow/lite/python/optimize/
cp tensorflow/tensorflow/lite/python/testdata/BUILD vai_q_tensorflow/tensorflow/lite/python/testdata/
cp tensorflow/tensorflow/lite/schema/BUILD vai_q_tensorflow/tensorflow/lite/schema/
cp tensorflow/tensorflow/lite/schema/builtin_ops_header/BUILD vai_q_tensorflow/tensorflow/lite/schema/builtin_ops_header/
cp tensorflow/tensorflow/lite/testing/BUILD vai_q_tensorflow/tensorflow/lite/testing/
cp tensorflow/tensorflow/lite/toco/BUILD vai_q_tensorflow/tensorflow/lite/toco/
cp tensorflow/tensorflow/lite/toco/graph_transformations/tests/BUILD vai_q_tensorflow/tensorflow/lite/toco/graph_transformations/tests/
cp tensorflow/tensorflow/lite/toco/tensorflow_graph_matching/BUILD vai_q_tensorflow/tensorflow/lite/toco/tensorflow_graph_matching/
cp tensorflow/tensorflow/lite/toco/tflite/BUILD vai_q_tensorflow/tensorflow/lite/toco/tflite/
cp tensorflow/tensorflow/lite/tools/BUILD vai_q_tensorflow/tensorflow/lite/tools/
cp tensorflow/tensorflow/lite/tools/accuracy/ilsvrc/BUILD vai_q_tensorflow/tensorflow/lite/tools/accuracy/ilsvrc/
cp tensorflow/tensorflow/lite/tools/benchmark/BUILD vai_q_tensorflow/tensorflow/lite/tools/benchmark/
cp tensorflow/tensorflow/lite/tools/evaluation/stages/BUILD vai_q_tensorflow/tensorflow/lite/tools/evaluation/stages/
cp tensorflow/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/BUILD vai_q_tensorflow/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/
cp tensorflow/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/BUILD vai_q_tensorflow/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/
cp tensorflow/tensorflow/lite/tools/optimize/BUILD vai_q_tensorflow/tensorflow/lite/tools/optimize/
cp tensorflow/tensorflow/lite/tools/optimize/calibration/BUILD vai_q_tensorflow/tensorflow/lite/tools/optimize/calibration/
cp tensorflow/tensorflow/lite/tutorials/BUILD vai_q_tensorflow/tensorflow/lite/tutorials/
